import { firebaseConfig, allowedEmails } from './firebase-config.js';

const DEPARTMENTS=['Media & Communications','Impact & Outreach','Events & Operations','Partnerships & Development'];
const LEVELS=['Explorer','Contributor','Owner','Lead'];
const CHECKS=[
  ['attended','Katıldı',1],['tookTask','Görev aldı',1],['completed','Görevi tamamladı',2],['onTime','Zamanında tamamladı',1],
  ['initiativeFlag','İnisiyatif aldı',1],['projectIdea','Proje fikri getirdi',1],['helpedTeam','Takıma destek oldu',1],
  ['eventOutreach','Etkinlik / Outreach',1],['output','Somut çıktı üretti',2]
];
const RATINGS=[['responsibility','Sorumluluk'],['initiative','İnisiyatif'],['teamwork','Takım çalışması'],['projectProduction','Proje üretimi'],['leadership','Liderlik']];
const MAX_SCORE=CHECKS.reduce((a,x)=>a+x[2],0)+RATINGS.length*3;
const state={students:[],evaluations:[],mode:'local',user:null,db:null,auth:null,fb:null};
const $=s=>document.querySelector(s); const $$=s=>[...document.querySelectorAll(s)];
const today=()=>new Date().toISOString().slice(0,10);
const uid=()=>crypto.randomUUID?.() || `id-${Date.now()}-${Math.random().toString(16).slice(2)}`;
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
function toast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2200)}
function configured(){return firebaseConfig.apiKey && !firebaseConfig.apiKey.includes('REPLACE_ME') && firebaseConfig.projectId && !firebaseConfig.projectId.includes('REPLACE_ME')}
function saveLocal(){localStorage.setItem('irs_students',JSON.stringify(state.students));localStorage.setItem('irs_evaluations',JSON.stringify(state.evaluations))}
function loadLocal(){state.students=JSON.parse(localStorage.getItem('irs_students')||'[]');state.evaluations=JSON.parse(localStorage.getItem('irs_evaluations')||'[]')}
async function initFirebase(){
  if(!configured()){loadLocal();state.mode='local';$('#storageBadge').textContent='Yerel Demo · Bu cihaz';return true}
  const appMod=await import('https://www.gstatic.com/firebasejs/11.0.2/firebase-app.js');
  const authMod=await import('https://www.gstatic.com/firebasejs/11.0.2/firebase-auth.js');
  const fsMod=await import('https://www.gstatic.com/firebasejs/11.0.2/firebase-firestore.js');
  const app=appMod.initializeApp(firebaseConfig);state.auth=authMod.getAuth(app);state.db=fsMod.getFirestore(app);state.fb={...authMod,...fsMod};state.mode='firebase';
  $('#storageBadge').textContent='Cloud Firestore · Kalıcı';
  return new Promise(resolve=>authMod.onAuthStateChanged(state.auth,async user=>{
    if(!user){$('#loginGate').classList.remove('hidden');resolve(false);return}
    if(allowedEmails?.length && !allowedEmails.includes(user.email)){await authMod.signOut(state.auth);alert('Bu Google hesabı yetkili listesinde değil.');resolve(false);return}
    state.user=user;$('#loginGate').classList.add('hidden');$('#logoutBtn').classList.remove('hidden');$('#userLabel').textContent=user.email;await refreshCloud();resolve(true)
  }))
}
async function refreshCloud(){
  const {collection,getDocs,query,orderBy}=state.fb;
  const ss=await getDocs(query(collection(state.db,'students'),orderBy('name')));state.students=ss.docs.map(d=>({id:d.id,...d.data()}));
  const es=await getDocs(query(collection(state.db,'evaluations'),orderBy('date','desc')));state.evaluations=es.docs.map(d=>({id:d.id,...d.data()}));
}
async function saveStudent(data){
  if(state.mode==='local'){const i=state.students.findIndex(x=>x.id===data.id);if(i>=0)state.students[i]=data;else state.students.push(data);saveLocal();return}
  const {doc,setDoc,serverTimestamp}=state.fb;await setDoc(doc(state.db,'students',data.id),{...data,updatedAt:serverTimestamp()},{merge:true});await refreshCloud();
}
async function removeStudent(id){
  if(state.mode==='local'){state.students=state.students.filter(x=>x.id!==id);state.evaluations=state.evaluations.filter(x=>x.studentId!==id);saveLocal();return}
  const {doc,deleteDoc,getDocs,query,collection,where}=state.fb;await deleteDoc(doc(state.db,'students',id));const q=await getDocs(query(collection(state.db,'evaluations'),where('studentId','==',id)));await Promise.all(q.docs.map(d=>deleteDoc(d.ref)));await refreshCloud();
}
async function saveEvaluation(data){
  if(state.mode==='local'){state.evaluations.push(data);saveLocal();return}
  const {doc,setDoc,serverTimestamp}=state.fb;await setDoc(doc(state.db,'evaluations',data.id),{...data,createdAt:serverTimestamp()});await refreshCloud();
}
async function removeEvaluation(id){if(state.mode==='local'){state.evaluations=state.evaluations.filter(x=>x.id!==id);saveLocal()}else{await state.fb.deleteDoc(state.fb.doc(state.db,'evaluations',id));await refreshCloud()}}
function scoreEval(e){return CHECKS.reduce((s,[k,,w])=>s+(e[k]?w:0),0)+RATINGS.reduce((s,[k])=>s+Number(e[k]||0),0)}
function studentEvals(id){return state.evaluations.filter(e=>e.studentId===id).sort((a,b)=>b.date.localeCompare(a.date))}
function readiness(student){
  const ev=studentEvals(student.id).slice(0,4); if(!ev.length)return {pct:0,label:'İlk değerlendirme bekleniyor'};
  const count=k=>ev.filter(x=>x[k]).length, avg=k=>ev.reduce((s,x)=>s+Number(x[k]||0),0)/ev.length;
  let checks=[];
  if(student.level==='Explorer')checks=[[count('attended'),3],[count('completed'),3],[avg('teamwork'),1.5],[avg('responsibility'),1.5]];
  else if(student.level==='Contributor')checks=[[count('completed'),3],[count('output'),2],[avg('responsibility'),2],[avg('initiative'),1.5]];
  else if(student.level==='Owner')checks=[[count('helpedTeam'),2],[count('output'),2],[avg('leadership'),2],[avg('teamwork'),2],[avg('initiative'),2]];
  else return {pct:100,label:'Lead · gelişim sürüyor'};
  const pct=Math.round(checks.reduce((s,[v,t])=>s+Math.min(v/t,1),0)/checks.length*100);return {pct,label:`${LEVELS[Math.min(LEVELS.indexOf(student.level)+1,3)]} için %${pct}`}
}
function latestEval(s){return studentEvals(s.id)[0]}
function daysSince(date){if(!date)return 999;return Math.floor((Date.now()-new Date(date+'T12:00:00').getTime())/86400000)}
function renderKpis(){const active=state.students.filter(s=>s.active!==false).length, recent=state.evaluations.filter(e=>daysSince(e.date)<=7).length;const cards=[['Kayıtlı Öğrenci',state.students.length,'Sistemdeki toplam'],['Aktif Öğrenci',active,'Aktif işaretli'],['Bu Hafta Değerlendirme',recent,'Son 7 gün'],['Contributor+',state.students.filter(s=>LEVELS.indexOf(s.level)>=1).length,'Contributor / Owner / Lead'],['Owner + Lead',state.students.filter(s=>LEVELS.indexOf(s.level)>=2).length,'Sahiplik ve liderlik']];$('#kpiGrid').innerHTML=cards.map(c=>`<div class="kpi-card"><div class="label">${c[0]}</div><div class="value">${c[1]}</div><div class="sub">${c[2]}</div></div>`).join('')}
function renderDashboard(){renderKpis();const dep=$('#departmentFilter').value||'all';const students=state.students.filter(s=>dep==='all'||s.department===dep);$('#studentSummary').innerHTML=students.length?students.map(s=>{const r=readiness(s),le=latestEval(s);return `<div class="student-row"><div class="student-name"><strong>${esc(s.name)}</strong><span>${esc(s.grade)}. sınıf · ${esc(s.department)}</span></div><div><span class="level-pill">${esc(s.level)}</span></div><div><div class="progress"><span style="width:${r.pct}%"></span></div><div class="progress-label">${r.label}</div></div><div class="progress-label">${le?le.date:'Kayıt yok'}</div></div>`}).join(''):'<div class="empty">Henüz öğrenci yok.</div>';
  const attention=state.students.map(s=>({s,le:latestEval(s)})).filter(x=>!x.le||daysSince(x.le.date)>14||studentEvals(x.s.id).slice(0,2).every(e=>!e.completed&& !e.output)).slice(0,8);$('#attentionList').innerHTML=attention.length?attention.map(x=>`<div class="attention-item"><strong>${esc(x.s.name)}</strong><p>${!x.le?'Henüz değerlendirme yok.':daysSince(x.le.date)>14?'14+ gündür değerlendirme yok.':'Son değerlendirmelerde tamamlanan iş görünmüyor.'}</p></div>`).join(''):'<div class="empty">Şu anda belirgin bir risk görünmüyor.</div>'}
function renderStudents(){const q=$('#studentSearch').value?.toLowerCase()||'';const arr=state.students.filter(s=>s.name.toLowerCase().includes(q));$('#studentTable').innerHTML=`<table class="data-table"><thead><tr><th>Ad Soyad</th><th>Sınıf</th><th>Departman</th><th>Seviye</th><th>Aktif</th><th></th></tr></thead><tbody>${arr.map(s=>`<tr><td><strong>${esc(s.name)}</strong></td><td>${esc(s.grade)}</td><td>${esc(s.department)}</td><td><span class="level-pill">${esc(s.level)}</span></td><td>${s.active!==false?'Evet':'Hayır'}</td><td><div class="table-actions"><button class="icon-btn" data-edit="${s.id}">Düzenle</button><button class="icon-btn" data-eval="${s.id}">Değerlendir</button><button class="icon-btn danger" data-del="${s.id}">Sil</button></div></td></tr>`).join('')}</tbody></table>`;bindTableActions()}
function renderSelectors(){const opts=state.students.map(s=>`<option value="${s.id}">${esc(s.name)} · ${esc(s.grade)} · ${esc(s.level)}</option>`).join('');$('#evalStudent').innerHTML='<option value="">Öğrenci seç</option>'+opts;$('#historyStudentFilter').innerHTML='<option value="all">Tüm Öğrenciler</option>'+opts;DEPARTMENTS.forEach(()=>{});}
function renderProfile(id){const s=state.students.find(x=>x.id===id);if(!s){$('#selectedStudentProfile').innerHTML='<div class="empty">Listeden bir öğrenci seç.</div>';return}const ev=studentEvals(id),last=ev[0],r=readiness(s),avg=ev.length?Math.round(ev.reduce((a,x)=>a+scoreEval(x),0)/ev.length):0;$('#selectedStudentProfile').innerHTML=`<div class="profile-card"><div class="profile-top"><div><h3>${esc(s.name)}</h3><p>${esc(s.grade)}. sınıf · ${esc(s.department)}</p></div><span class="level-pill">${esc(s.level)}</span></div><div><div class="progress"><span style="width:${r.pct}%"></span></div><div class="progress-label">${r.label}</div></div><div class="mini-stats"><div class="mini-stat"><span>Değerlendirme</span><strong>${ev.length}</strong></div><div class="mini-stat"><span>Ort. Skor</span><strong>${avg}</strong></div><div class="mini-stat"><span>Son Kayıt</span><strong style="font-size:12px">${last?.date||'—'}</strong></div></div><div class="note-box"><strong>Genel Mentor Notu</strong><br>${esc(s.note||'Not yok')}</div>${last?`<div class="note-box"><strong>Sonraki Adım</strong><br>${esc(last.nextStep||'Belirtilmedi')}</div>`:''}</div>`}
function renderHistory(){const sid=$('#historyStudentFilter').value||'all',lev=$('#historyLevelFilter').value||'all';const rows=state.evaluations.filter(e=>sid==='all'||e.studentId===sid).filter(e=>{const s=state.students.find(x=>x.id===e.studentId);return lev==='all'||s?.level===lev}).sort((a,b)=>b.date.localeCompare(a.date));$('#historyTable').innerHTML=`<table class="data-table"><thead><tr><th>Tarih</th><th>Öğrenci</th><th>Skor</th><th>Tamamladı</th><th>Çıktı</th><th>Not</th><th></th></tr></thead><tbody>${rows.map(e=>{const s=state.students.find(x=>x.id===e.studentId);return `<tr><td>${e.date}</td><td>${esc(s?.name||'Silinmiş öğrenci')}</td><td><strong>${scoreEval(e)}/${MAX_SCORE}</strong></td><td>${e.completed?'✓':'—'}</td><td>${e.output?'✓':'—'}</td><td>${esc((e.note||'').slice(0,80))}</td><td><button class="icon-btn danger" data-edel="${e.id}">Sil</button></td></tr>`}).join('')}</tbody></table>`;$$('[data-edel]').forEach(b=>b.onclick=async()=>{if(confirm('Bu değerlendirme silinsin mi?')){await removeEvaluation(b.dataset.edel);renderAll();toast('Değerlendirme silindi')}})}
function renderScoring(){const rows=[...CHECKS.map(x=>[x[1],`+${x[2]}`]),...RATINGS.map(x=>[x[1],'0–3']),['Toplam maksimum',MAX_SCORE],['Seviye ilerlemesi','Son 4 kayıt + eşikler']];$('#scoringInfo').innerHTML=rows.map(r=>`<div class="settings-row"><span>${r[0]}</span><strong>${r[1]}</strong></div>`).join('')}
function renderAll(){renderDashboard();renderStudents();renderSelectors();renderHistory();renderScoring();const current=$('#evalStudent').value;renderProfile(current)}
function bindTableActions(){$$('[data-edit]').forEach(b=>b.onclick=()=>editStudent(b.dataset.edit));$$('[data-eval]').forEach(b=>b.onclick=()=>{go('evaluate');$('#evalStudent').value=b.dataset.eval;renderProfile(b.dataset.eval)});$$('[data-del]').forEach(b=>b.onclick=async()=>{if(confirm('Öğrenci ve değerlendirme kayıtları silinsin mi?')){await removeStudent(b.dataset.del);renderAll();toast('Öğrenci silindi')}})}
function resetStudentForm(){ $('#studentForm').reset();$('#studentId').value='';$('#studentLevel').value='Explorer';$('#studentStartDate').value=today();$('#studentActive').checked=true;$('#studentFormTitle').textContent='Yeni Öğrenci'}
function editStudent(id){const s=state.students.find(x=>x.id===id);if(!s)return;$('#studentId').value=s.id;$('#studentName').value=s.name;$('#studentGrade').value=s.grade;$('#studentDepartment').value=s.department;$('#studentLevel').value=s.level;$('#studentStartDate').value=s.startDate;$('#studentActive').checked=s.active!==false;$('#studentNote').value=s.note||'';$('#studentFormTitle').textContent='Öğrenciyi Düzenle';go('students');window.scrollTo({top:0,behavior:'smooth'})}
function go(page){$$('.page').forEach(x=>x.classList.toggle('active',x.id===page));$$('.nav-item').forEach(x=>x.classList.toggle('active',x.dataset.page===page));const meta={dashboard:['Özet','Takımın ve öğrencilerin güncel gelişim görünümü.'],students:['Öğrenciler','Yeni öğrenci ekle, düzenle ve temel bilgileri yönet.'],evaluate:['Değerlendir','Haftalık hızlı işaretleme, gelişim puanı ve mentor notu.'],history:['Kayıtlar','Geçmiş değerlendirmeleri incele.'],settings:['Ayarlar & Yedek','Puanlama mantığı, veri dışa aktarma ve kurulum.']}[page];$('#pageTitle').textContent=meta[0];$('#pageSubtitle').textContent=meta[1]}
function buildInputs(){DEPARTMENTS.forEach(d=>{$('#studentDepartment').insertAdjacentHTML('beforeend',`<option>${d}</option>`);$('#departmentFilter').insertAdjacentHTML('beforeend',`<option>${d}</option>`)});$('#checkGrid').innerHTML=CHECKS.map(([k,l])=>`<label class="check-card"><input type="checkbox" id="c_${k}" data-score-input><span>${l}</span></label>`).join('');$('#ratingGrid').innerHTML=RATINGS.map(([k,l])=>`<div class="rating-line"><label>${l}</label><input type="range" id="r_${k}" min="0" max="3" value="0" step="1" data-score-input><output id="o_${k}">0</output></div>`).join('');$$('[data-score-input]').forEach(x=>x.addEventListener('input',()=>{RATINGS.forEach(([k])=>$('#o_'+k).value=$('#r_'+k).value);const temp={};CHECKS.forEach(([k])=>temp[k]=$('#c_'+k).checked);RATINGS.forEach(([k])=>temp[k]=Number($('#r_'+k).value));$('#scorePreview').textContent=`${scoreEval(temp)} / ${MAX_SCORE}`}))}
function resetEval(){ $('#evaluationForm').reset();$('#evalDate').value=today();RATINGS.forEach(([k])=>{$('#r_'+k).value=0;$('#o_'+k).value=0});$('#scorePreview').textContent=`0 / ${MAX_SCORE}`;renderProfile($('#evalStudent').value)}
function download(name,text,type='application/json'){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([text],{type}));a.download=name;a.click();URL.revokeObjectURL(a.href)}
function exportCsv(){const h=['date','studentId','studentName',...CHECKS.map(x=>x[0]),...RATINGS.map(x=>x[0]),'score','note','nextStep'];const rows=state.evaluations.map(e=>{const s=state.students.find(x=>x.id===e.studentId);return [e.date,e.studentId,s?.name||'',...CHECKS.map(([k])=>e[k]?'1':'0'),...RATINGS.map(([k])=>e[k]||0),scoreEval(e),e.note||'',e.nextStep||'']});const csv=[h,...rows].map(r=>r.map(v=>`"${String(v).replaceAll('"','""')}"`).join(',')).join('\n');download(`irs-evaluations-${today()}.csv`,csv,'text/csv;charset=utf-8')}
async function main(){buildInputs();$('#studentStartDate').value=today();$('#evalDate').value=today();$$('.nav-item').forEach(b=>b.onclick=()=>go(b.dataset.page));$('#quickAddBtn').onclick=()=>{go('students');resetStudentForm()};$('#studentFormReset').onclick=resetStudentForm;$('#evalReset').onclick=resetEval;$('#studentSearch').oninput=renderStudents;$('#departmentFilter').onchange=renderDashboard;$('#historyStudentFilter').onchange=renderHistory;$('#historyLevelFilter').onchange=renderHistory;$('#evalStudent').onchange=e=>renderProfile(e.target.value);
  $('#studentForm').onsubmit=async e=>{e.preventDefault();const id=$('#studentId').value||uid();await saveStudent({id,name:$('#studentName').value.trim(),grade:$('#studentGrade').value,department:$('#studentDepartment').value,level:$('#studentLevel').value,startDate:$('#studentStartDate').value,active:$('#studentActive').checked,note:$('#studentNote').value.trim()});resetStudentForm();renderAll();toast('Öğrenci kaydedildi')};
  $('#evaluationForm').onsubmit=async e=>{e.preventDefault();const studentId=$('#evalStudent').value;if(!studentId)return;const data={id:uid(),studentId,date:$('#evalDate').value,note:$('#evalNote').value.trim(),nextStep:$('#evalNext').value.trim()};CHECKS.forEach(([k])=>data[k]=$('#c_'+k).checked);RATINGS.forEach(([k])=>data[k]=Number($('#r_'+k).value));data.score=scoreEval(data);await saveEvaluation(data);resetEval();renderAll();$('#evalStudent').value=studentId;renderProfile(studentId);toast('Değerlendirme kaydedildi')};
  $('#exportJsonBtn').onclick=()=>download(`irs-backup-${today()}.json`,JSON.stringify({version:1,exportedAt:new Date().toISOString(),students:state.students,evaluations:state.evaluations},null,2));$('#exportCsvBtn').onclick=exportCsv;$('#importJsonInput').onchange=async e=>{if(state.mode!=='local'){toast('İçe aktarma yalnız yerel demo modunda aktif.');return}const f=e.target.files[0];if(!f)return;try{const d=JSON.parse(await f.text());state.students=d.students||[];state.evaluations=d.evaluations||[];saveLocal();renderAll();toast('Yedek yüklendi')}catch{alert('Geçerli bir IRS JSON yedeği değil.')}};
  $('#loginBtn').onclick=async()=>{const p=new state.fb.GoogleAuthProvider();await state.fb.signInWithPopup(state.auth,p)};$('#logoutBtn').onclick=async()=>{await state.fb.signOut(state.auth);location.reload()};
  const ready=await initFirebase();if(ready){renderAll();resetStudentForm();resetEval()}
}
main().catch(err=>{console.error(err);alert('Uygulama başlatılamadı: '+err.message)});
